# Generated by Django 5.0.3 on 2024-03-24 03:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="price",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="quantity",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AlterField(
            model_name="trader",
            name="apples",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="trader",
            name="bananas",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="trader",
            name="capital",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="trader",
            name="cherries",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="trader",
            name="dragonfruit",
            field=models.PositiveIntegerField(),
        ),
    ]
