# Generated by Django 5.0.3 on 2024-03-28 05:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="order_type",
            new_name="side",
        ),
    ]
