# Generated by Django 5.0.3 on 2024-03-31 14:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0002_rename_order_type_order_side"),
    ]

    operations = [
        migrations.RenameField(
            model_name="trader",
            old_name="apples",
            new_name="asset_1",
        ),
        migrations.RenameField(
            model_name="trader",
            old_name="apples_remaining",
            new_name="asset_1_remaining",
        ),
        migrations.RenameField(
            model_name="trader",
            old_name="bananas",
            new_name="asset_2",
        ),
        migrations.RenameField(
            model_name="trader",
            old_name="bananas_remaining",
            new_name="asset_2_remaining",
        ),
        migrations.RenameField(
            model_name="trader",
            old_name="cherries",
            new_name="asset_3",
        ),
        migrations.RenameField(
            model_name="trader",
            old_name="cherries_remaining",
            new_name="asset_3_remaining",
        ),
        migrations.RenameField(
            model_name="trader",
            old_name="dragonfruit",
            new_name="asset_4",
        ),
        migrations.RenameField(
            model_name="trader",
            old_name="dragonfruit_remaining",
            new_name="asset_4_remaining",
        ),
    ]
