# Generated by Django 5.0.3 on 2024-03-31 14:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0003_rename_apples_trader_asset_1_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trader",
            name="asset_4",
        ),
        migrations.RemoveField(
            model_name="trader",
            name="asset_4_remaining",
        ),
        migrations.AddField(
            model_name="trader",
            name="asset_0",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="trader",
            name="asset_0_remaining",
            field=models.IntegerField(default=0),
        ),
    ]
