# Generated by Django 5.0.3 on 2024-04-03 01:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0004_remove_trader_asset_4_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="asset",
            field=models.IntegerField(
                choices=[
                    (0, "Dressing"),
                    (1, "Rye"),
                    (2, "Swiss"),
                    (3, "Pastrami"),
                ],
                db_index=True,
            ),
        ),
    ]
